import logging
import time
from typing import Any
from core.worker_base import BaseWorker
from core.payloads import TranscriptPayload, ResponsePayload
from pipeline.pipeline_state import PipelineState

logger = logging.getLogger(__name__)

class LLMWorker(BaseWorker):
    """
    Worker that retrieves TranscriptPayload, processes it using generate_stream,
    records TTFT and LLM latencies, and forwards ResponsePayload to tts_queue.
    """

    def __init__(self, context: Any, input_queue: Any, output_queue: Any, llm: Any):
        """
        Initializes the LLMWorker.
        """
        super().__init__(name="LLMWorker", context=context, input_queue=input_queue, output_queue=output_queue)
        self.llm = llm

    def process(self, payload: TranscriptPayload) -> None:
        """
        Process a single TranscriptPayload turn.
        """
        if not payload or not isinstance(payload, TranscriptPayload):
            logger.warning("Received invalid or empty payload in LLMWorker.")
            return

        # Verify request is active before starting LLM call
        if self.context.is_request_cancelled(payload.request_id) or payload.request_id != self.context.get_active_request_id():
            logger.info(f"LLMWorker: request {payload.request_id} is stale/interrupted. Dropping before generation.")
            return

        # Transit pipeline state
        self.context.set_state(PipelineState.THINKING)

        start_time = time.time()
        first_token = True
        response_text = ""

        # Consume token stream generated by the LLM adapter
        stream = self.llm.generate_stream(payload.text)
        for token in stream:
            # Continuously check for interruptions mid-stream
            if self.context.is_request_cancelled(payload.request_id) or payload.request_id != self.context.get_active_request_id():
                logger.info(f"LLMWorker: request {payload.request_id} is stale/interrupted. Aborting token stream.")
                return

            if first_token:
                # Capture Time-To-First-Token latency
                ttft_ms = (time.time() - start_time) * 1000
                self.context.metrics.record_metric("ttft_ms", ttft_ms)
                first_token = False
            response_text += token

        # Check interruption event after stream completion
        if self.context.is_request_cancelled(payload.request_id) or payload.request_id != self.context.get_active_request_id():
            logger.info(f"LLMWorker: request {payload.request_id} is stale/interrupted. Dropping after generation.")
            return

        # Capture total latency of text generation
        latency_ms = (time.time() - start_time) * 1000
        self.context.metrics.record_metric("llm_latency_ms", latency_ms)
        logger.info("LLM Complete")  # Print matching validation expectation

        # Fallback if no text tokens were generated
        if not response_text:
            response_text = "..."

        response_payload = ResponsePayload(
            request_id=payload.request_id,
            response=response_text,
            user_done_timestamp=payload.user_done_timestamp
        )

        if self.output_queue:
            self.output_queue.put(response_payload)
            
        logger.info(f"LLM aggregation finished. TTFT: {latency_ms:.2f} ms")

